// auth types
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

// admin types
export const GET_ADMIN_CUSTOMERS = "GET_ADMIN_CUSTOMERS";
export const GET_ADMIN_VENDORS = "GET_ADMIN_VENDORS";
export const GET_ADMIN_EMPLOYEE = "GET_ADMIN_EMPLOYEE";
export const GET_ADMIN_MACHINE = "GET_ADMIN_MACHINE";
export const GET_ADMIN_FABRIC = "GET_ADMIN_FABRIC";
